### ISSUE TITLE
Tello Video

### ISSUE THREAD

**Issue by ozanpkr** [alexmihalyk23/jetsonMobileNet#1]
I am sorry to write here.I deal with tello video.My project is about yolov2 so ı must get frame with high FPS such as 20-25.When ı connected tello by udp, fps decreases and ı get huge delay.I use python 3.6.Can you help me,it is very significant for me :(

**Comment by alexmihalyk23** [comment]
does this problem occur when you expect a response from tello? If yes, then try to remove the waiting for an answer in the tello library

**Comment by ozanpkr** [comment]
> does this problem occur when you expect a response from tello? If yes, then try to remove the waiting for an answer in the tello library
I tried that .The frame came a little faster.But not enough for YOLOv2.Can you give another suggestion for get 20 FPS? Also , I use djıtellopy 1.5 library. It use this code for get frame;

        tello.cap = cv2.VideoCapture(address)
        self.cap = tello.cap
        if not self.cap.isOpened():
        self.cap.open(address)
        self.grabbed, self.frame = self.cap.read()

**Comment by alexmihalyk23** [comment]
Try webcamvideostream in imutils library
`Videocapture =webcamvideostream(address).start()`

And remove ret

**Comment by alexmihalyk23** [comment]
please reply if possible

**Comment by alexmihalyk23** [comment]
if you have a project on github please send a link

**Comment by ozanpkr** [comment]
> if you have a project on github please send a link

https://drive.google.com/open?id=1ybxjD3ZH5PclnI53dj3WK010-geS-VfF

in this url include my work. If ı want summary ,ı can say;
you run test.val.py for start project and I use djıtellopy library for drone connect.Also I use that code line for get frame. 'get_frame_read' function is in djıtellpy library for get frame.But it is very slow for me.Minimum 20 FPS necessary for project.Please help me brother.Thanks for everything.
image = drone.get_frame_read().frame

**Comment by alexmihalyk23** [comment]
for faster answers I suggest to communicate in telegram https://t.me/joinchat/GF-WbBYBmn3tAnxcpzzhHQ
